import type { Repository } from '../interfaces/repository'
import type { ApiResponse } from '../../../src/types/common'
import type {
  ReadingEvent,
  ReadingEventParams,
  ReadingPlan,
  ReadingPlanCreateParams,
  ReadingStat,
} from '../../../src/types/reading'
import { ErrorCode } from '../../../src/types/common'
import { fail, success } from '../common/response'
import { validateParams } from '../common/validate'

const USER_RECORDED_EVENTS = new Set<ReadingEvent['eventType']>(['discussion', 'group_activity'])

export async function handleCreateReadingPlan(
  repo: Repository,
  openid: string,
  params: ReadingPlanCreateParams,
): Promise<ApiResponse<ReadingPlan>> {
  const validationError = validateParams<ReadingPlan>(params as unknown as Record<string, unknown>, [
    { name: 'bookId', type: 'string', required: true },
  ])
  if (validationError) return validationError

  if (params.targetDate && Number.isNaN(Date.parse(params.targetDate))) {
    return fail(ErrorCode.BAD_REQUEST, 'targetDate must be a valid date')
  }
  const today = new Date().toISOString().slice(0, 10)
  if (params.targetDate && params.targetDate.slice(0, 10) < today) {
    return fail(ErrorCode.BAD_REQUEST, 'targetDate must be today or later')
  }

  const book = await repo.findBookById(params.bookId)
  if (!book) return fail(ErrorCode.NOT_FOUND, 'Book not found')

  const now = Date.now()
  const plan = await repo.createReadingPlan({
    openid,
    bookId: params.bookId,
    targetDate: params.targetDate,
    status: 'active',
    createdAt: now,
    updatedAt: now,
  })
  await repo.addReadingEvent({
    openid,
    bookId: params.bookId,
    eventType: 'plan_started',
    source: 'system',
    createdAt: now,
  })
  return success(plan)
}

export async function handleListReadingPlans(
  repo: Repository,
  openid: string,
): Promise<ApiResponse<ReadingPlan[]>> {
  return success(await repo.listReadingPlans(openid))
}

export async function handleCompleteReadingPlan(
  repo: Repository,
  openid: string,
  planId: string,
): Promise<ApiResponse<ReadingPlan>> {
  if (!planId) return fail(ErrorCode.BAD_REQUEST, 'planId is required')
  const plan = (await repo.listReadingPlans(openid)).find((item) => item.planId === planId)
  if (!plan) return fail(ErrorCode.NOT_FOUND, 'Reading plan not found')
  if (plan.status === 'completed') return success(plan)
  if (plan.status === 'cancelled') return fail(ErrorCode.BAD_REQUEST, 'Cancelled plan cannot be completed')

  const updated = await repo.updateReadingPlan(planId, openid, { status: 'completed' })
  await repo.addReadingEvent({
    openid,
    bookId: plan.bookId,
    eventType: 'plan_completed',
    source: 'system',
    createdAt: Date.now(),
  })
  return success(updated)
}

export async function handleRecordParticipation(
  repo: Repository,
  openid: string,
  params: ReadingEventParams,
): Promise<ApiResponse<ReadingEvent>> {
  const validationError = validateParams<ReadingEvent>(params as unknown as Record<string, unknown>, [
    { name: 'bookId', type: 'string', required: true },
    { name: 'eventType', type: 'string', required: true },
  ])
  if (validationError) return validationError
  if (!USER_RECORDED_EVENTS.has(params.eventType)) {
    return fail(ErrorCode.FORBIDDEN, 'This event can only be generated by the server')
  }

  const book = await repo.findBookById(params.bookId)
  if (!book) return fail(ErrorCode.NOT_FOUND, 'Book not found')
  const membershipGroupId = params.groupId ?? params.classId
  if (membershipGroupId && !(await repo.findCommunityMember(membershipGroupId, openid))) {
    return fail(ErrorCode.ACCESS_DENIED, 'Not a member of this group')
  }

  const event = await repo.addReadingEvent({
    openid,
    bookId: params.bookId,
    eventType: params.eventType,
    source: 'user',
    groupId: params.groupId,
    classId: params.classId,
    createdAt: Date.now(),
  })
  return success(event)
}

export async function handleListReadingEvents(
  repo: Repository,
  openid: string,
  bookId?: string,
): Promise<ApiResponse<ReadingEvent[]>> {
  return success(await repo.listReadingEvents(openid, bookId))
}

export async function handleReadingStat(
  repo: Repository,
  openid: string,
): Promise<ApiResponse<ReadingStat>> {
  return success(await repo.getReadingStat(openid))
}
